[project]
name = "hackerrank-orchestrate-august26-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=2.16.0",
    "groq>=1.6.0",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]
